.\" $Id$
.\"
.Dd Janunary 15, 2007
.Dt IMERGE 1
.Sh NAME
.Nm imerge
.Nd help merge one file to another interactively
.Sh SYNOPSIS
.Nm
.Op Fl x Ar diff_flags
.Op Fl X Ar sdiff_flags
.Ar source
.Ar destination
.Sh DESCRIPTION
The
.Nm
command is a utility to help merge one file to another interactively.
.Pp
If given files both exist and are identical, it silently exits without
doing anything.
.Pp
If given files both exist and they differ, differences are shown using
the
.Xr diff 1
command and user is asked if the source file should be installed to
the destination, they should be edited first, or the source file
should be merged into the destination file interactively using the
.Xr sdiff 1
command.
.Pp
If the source file is missing, user is asked if the destination file
should be deleted.
.Pp
If the destination file is missing, user is asked if the source file
should be installed to the destination.
.Pp
Currently symbolic links are not supported.  If either of given files
is a symbolic link, no operation is performed.
.Pp
.Sh OPTIONS
The following command line arguments are supported:
.Pp
.Bl -tag -width "-X sdiff_flags" -compact
.It Fl x Ar diff_flags
Set command line flags for
.Xr diff 1
to
.Ar diff_flags .
The default value is
.Dq Fl u .
.Pp
.It Fl X Ar sdiff_flags
Set extra command line flags for
.Xr sdiff 1
to
.Ar sdiff_flags .
The default value is
.Dq Fl a Fl s .
.El
.Sh ENVIRONMENT
.Bl -tag -width "TMPDIR" -compact
.It Ev EDITOR
Name of the editor program to run when user chooses to edit files.
.Pp
.It Ev PAGER
Name of the pager program to run when showing differences.
.El
.Sh SEE ALSO
.Xr diff 1 ,
.Xr sdiff 1
.Sh HISTORY
The
.Nm
utility was first released on 15 January, 2007.
.Pp
This utility was (obviously) inspired by the
.Nm mergemaster
utility of
.Fx
in hope of using part of its functionality stand-alone.
.Sh AUTHORS
.An Akinori MUSHA Aq knu@iDaemons.org
.Pp
Licensed under the 2-clause BSD license.  See
.Pa LICENSE.txt
for details.
.Pp
Visit the GitHub repository (URL:
.Pa https://github.com/knu/imerge )
for the latest information and feedback.
