.\" $Id$
.\"
.Dd Janunary 3, 2007
.Dt IMERGE 1
.Os FreeBSD
.Sh NAME
.Nm imerge
.Nd merges two files interactively
.Sh SYNOPSIS
.Nm
.Ar source
.Ar destination
.Sh DESCRIPTION
The
.Nm
command is a utility to merge two files interactively.
.Pp
If given files both exist and are identical, it silently exits without
doing anything.
.Pp
If given files both exist and they differ, differences are shown using
the
.Xr diff 1
command and user is asked if the source file should be installed to
the destination, or merge the source file with the destination file
interactively using the
.Xr sdiff 1
command.
.Pp
If the source file is missing, user is asked if the destination file
should be deleted.
.Pp
If the destination file is missing, user is asked if the source file
should be installed to the destination.
.Pp
.Sh OPTIONS
There is no command line option defined at the moment.
.Pp
.Sh SEE ALSO
.Xr diff 1 ,
.Xr sdiff 1 ,
.Sh AUTHORS
.An Akinori MUSHA Aq knu@iDaemons.org
.Sh BUGS
There may be.  Use at your own risk.
